apiVersion: v1
kind: Service
metadata:
  name: vn-prototype-service
spec:
  type: LoadBalancer
  loadBalancerIP: 34.81.249.188 # <-- PASTE YOUR RESERVED IP HERE
  selector:
    app: vn-prototype
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000